/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6 */

#ifndef PB_SENSOR_SENSOR_DATA_PB_H_INCLUDED
#define PB_SENSOR_SENSOR_DATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _sensor_SensorData {
    double temperature;
    double humidity;
    uint64_t timestamp;
    char device_id[32];
} sensor_SensorData;

typedef struct _sensor_SensorResponse {
    bool success;
    char message[128];
    bool has_data;
    sensor_SensorData data;
} sensor_SensorResponse;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define sensor_SensorData_init_default           {0, 0, 0, ""}
#define sensor_SensorResponse_init_default       {0, "", false, sensor_SensorData_init_default}
#define sensor_SensorData_init_zero              {0, 0, 0, ""}
#define sensor_SensorResponse_init_zero          {0, "", false, sensor_SensorData_init_default}

/* Field tags (for use in manual encoding/decoding) */
#define sensor_SensorData_temperature_tag        1
#define sensor_SensorData_humidity_tag           2
#define sensor_SensorData_timestamp_tag          3
#define sensor_SensorData_device_id_tag          4
#define sensor_SensorResponse_success_tag        1
#define sensor_SensorResponse_message_tag        2
#define sensor_SensorResponse_data_tag           3

/* Struct field encoding specification for nanopb */
#define sensor_SensorData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   temperature,      1) \
X(a, STATIC,   SINGULAR, DOUBLE,   humidity,         2) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,        3) \
X(a, STATIC,   SINGULAR, STRING,   device_id,        4)
#define sensor_SensorData_CALLBACK NULL
#define sensor_SensorData_DEFAULT NULL

#define sensor_SensorResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,          1) \
X(a, STATIC,   SINGULAR, STRING,   message,          2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  data,             3)
#define sensor_SensorResponse_CALLBACK NULL
#define sensor_SensorResponse_DEFAULT NULL
#define sensor_SensorResponse_data_MSGTYPE sensor_SensorData

extern const pb_msgdesc_t sensor_SensorData_msg;
extern const pb_msgdesc_t sensor_SensorResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define sensor_SensorData_fields &sensor_SensorData_msg
#define sensor_SensorResponse_fields &sensor_SensorResponse_msg

/* Maximum encoded size of messages (where known) */
#define sensor_SensorData_size                   69
#define sensor_SensorResponse_size               206

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif