/* Automatically generated nanopb source */
/* Generated by nanopb-0.4.6 */

#include "sensor_data.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(sensor_SensorData, sensor_SensorData, AUTO)

PB_BIND(sensor_SensorResponse, sensor_SensorResponse, AUTO)